travis:
  secure:
    BINSTAR_TOKEN: EiNm5HkbeKQ9SIOMFfCJj/9O2rBagE6XK7FZXpL56iuR6G4Mq4vsM4Oe8kCpdGy+J5A+o8EbLHNTQx2wQYBLhP9din0SGYZLvt7NeZ/o3PAyRoGw/ZKWa83dxQ6lXt9sjB+ab2KAUHlEbF8dmPAd1i8V0Wl4Nvn1ol2OChTZnmbzldEeoZ2Xp4aiconNo0VK2Us10Cf6moXJ9g5LV9Mepj4OZKK9kGdtnt9oxNMo39uiOEIMd5hz3zgokJ+jcqZaUKc1Pp4MHOEm133RJ3wB8llDUL6XGyPkoZx0yt8pDmXxgLBNJU2XRaJ2uQpNeif5XFPaAoHYk0G4iw9pQz/apCiZxsCDnLqlrnKVIJSvnDO68Xn6vJQWf9q5k2okR2R4qHLOuY0JeEg+FqOj7KOSINCNN/CvN2OuOkVx21NtVBVSY+WjGj725vLH8BTkdDyONJai9haMjutb00WIOwF3ROPEFop7bAnP49IHRFkz781/Kq64g14UP/+TeAKsdZ93m6Jxv7y+G/bBVIm5gMCghp7X8ELGBwTNtBVVoghI3mHRWzFCsP/aa+4CNWCf8yCMH37ksTU8pjG6f4EWHrwZEZyw+d+jlPn16NjVpxfYH6nlYwiZDwUiwJtRogNik1PQpDCXO5Xd29xiBbf/CIxd77A476KyCCD5ifYuiTqDbZA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
