travis:
  secure:
    BINSTAR_TOKEN: Npqp9BzT0Z+PzOq5aBQcWj5ICWKWDh4ipo83k0IO0J0SI8gofAMfW9ZBFTYxtSMtnUWMMkY1Ddgaeywn2myT4WYdLWufe2js2ZA4Vhu+LynB2X6tYodrw3XgFfAh47WjKJ3VjSN2Iy3dYeYX1XeKCsAoMeEn0xcHTdlkAmsgncMyTLtxgPWouviGTea3My4NORPpPmLJTvJ0hlw/ElHUEfIKzUOT4ySpHmsOh3S8KfM7ywyZcBGQctU9M27sG1h1qP8dD5N/PyXU5A17t0PyDtYQv93xLkGPGOz3/beXLeZqdElUuWcaQUbhcuKplKfIs6pyPHRR/CZoVpKzDzrA67YDjAdHPPYqWl+duvd01DQx0notlL43w3VAEEvtgUb/6MCaWWMsjlte+i0kdRQvxk51dWkhHORLvK5HzutO9MYNkLuBluN/B1js1lYvzbGuB43FVXOVVeeBGXpjPc5RycYYsrM1n8AHkzwGfVJdMDg5KyL9raVgAJXfMBNjVM9wY6Tjfig4plRi9xmjMvAKMz2m9t0/cvTATKVx5+PhoiKXs8VcBz/l+WbU5EJTAOS0/AGZx+Xbon77UueLpAFeOll3F+xMlGrpkZtn9PXvM2K97kYPPxd61CqGgc8My7v4VrYWE4eXZj75UNPky0ThSVy1Ni0+oSe5hduBBb3dbic=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
