travis:
  secure:
    BINSTAR_TOKEN: Dz0YunK3y1f+GCBk6ssv0Sa92Hc/nt9LRvhzAH2+mRN8R6FJfFHQCb6blS2AEsKa0hd8ZT3u8VNfaYo9acevIIYdsFzuj95oU4mVuQmB30aBWhWboCv5LO2rtl1jBSezgQ4e8Mf+GM7fEJwKmIitZOoo7SG6PrNffZfPGxi4vA4+7Y4TUQ46r7AhHa6g4+OimOEH7VAYNlGFYiWAg9CZQ22pxk6x/yn7/CDyuZO0064Z64/9XdL7xj7hIRW/cStEj8H/pnw7GqlEdnJdFPLJbnLfCVhWRiIziEiU+I1bP2TmjSi+XPIZMFcaiLvYtT2srDir44FMNeJSicCJPTGS5vXLWYBuk1pBLw+unFsErBQx8KVkTardZEWWZ8pv2K2KPfW9XdZQedZnj54f6/PgGM23a+6OhyfQs+BuGvXKQZ1Yws7+p1mLdP9y6NoNShr/sbs2F54cwIK19H8UKGv8nc2Jsr8Dqp2F5oQzvAXYbl7+zqkCXGmWNMS4xKJtTb0flIwDbt/xwWWCmHJN+DIIxY1jiwYWdzMHKvus1EgArZZHi4+Iz0iVj9bxgogEA1Nz0bq8A9/wf8RNgItIEJgPVYHBnt93RzTTChgHSZ6Olt6k7v73e/EASMQC+EDETUnc+gAiWNg3c9bdo5Jd2Yc1hFTS4Xrwxmfgh0oJjKZhyjs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
